x-app: &app
  restart: unless-stopped

services:
  backend:
    image: ghcr.io/aleksioprime/sk-survey-backend:${BACKEND_IMAGE_TAG:-latest}
    <<: *app
    container_name: sk-survey-backend
    networks:
      - apps_net

  frontend:
    image: ghcr.io/aleksioprime/sk-survey-frontend:${FRONTEND_IMAGE_TAG:-latest}
    <<: *app
    container_name: sk-survey-frontend
    depends_on:
      - backend
    networks:
      - apps_net

networks:
  apps_net:
    external: true
