x-app: &app
  env_file:
    - .env
  restart: unless-stopped

services:
  backend:
    build:
      context: ./backend
    <<: *app
    volumes:
      - ./backend/src:/usr/src/app/src
    ports:
      - "${BACKEND_PORT:-8000}:8000"

  frontend:
    build:
      context: ./frontend
      target: dev
      args:
        - VITE_LOGGING=${VITE_LOGGING}
        - VITE_BACKEND_API_URL=${VITE_BACKEND_API_URL}
    <<: *app
    environment:
      VITE_BACKEND_API_PROXY_URL: http://backend:8000/api/v1
    depends_on:
      - backend
    volumes:
      - ./frontend/app/src:/usr/src/app/src
    ports:
      - "${FRONTEND_PORT:-3000}:5173"
